name: Publish wheels

on:
  push:
    branches:
      - v[0-9]+.*
    tags:
      - v[0-9]+.*
  release:
    types:
      - published

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, macos]
        build: ["cp36-* cp37-* cp38-* cp39-*", "cp310-* cp311-* cp312-*"]
        x64image: [manylinux_2_17]
        nametag: [none]

        include:
          - os: ubuntu
            build: "cp38-manylinux_x86_64"
            x64image: manylinux2014
            nametag: focal

    steps:
      - name: Checkout pysam
        uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_BUILD: ${{ matrix.build }}
          CIBW_SKIP: "*-musllinux_*"
          CIBW_BUILD_VERBOSITY: 1

          CIBW_ARCHS_LINUX: x86_64
          CIBW_ARCHS_MACOS: x86_64

          CIBW_MANYLINUX_X86_64_IMAGE:  ${{ matrix.x64image }}
          CIBW_MANYLINUX_I686_IMAGE:    manylinux2014
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_17

      - name: Check wheelhouse
        run:  devtools/artifactname.py wheelhouse/*.whl >> $GITHUB_ENV
        env:
          NAMETAG: ${{ matrix.nametag }}

      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "wheelhouse/*.whl"
          allowUpdates: true
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
